/*********************************************************************
 * Name:      	main.cpp
 * Purpose:   	Implements simple wxWidgets application with GUI
 * 				created using wxFormBuilder.
 * Author:      Sala Carlo  
 * Created:   	01/02/2019
 * Copyright: 	
 * License:   	wxWidgets license (www.wxwidgets.org)
 * 
 * Notes:		Note that all GUI creation code is implemented in
 * 				guiApp.cpp source file which is generated by wxFormBuilder.
 *********************************************************************/

#include "main.h"

// initialize the application
IMPLEMENT_APP(MainApp);

////////////////////////////////////////////////////////////////////////////////
// application class implementation 
////////////////////////////////////////////////////////////////////////////////

bool MainApp::OnInit()
{
	#if wxUSE_XPM
	wxImage::AddHandler(new wxXPMHandler);
	#endif
	#if wxUSE_LIBPNG
	wxImage::AddHandler(new wxPNGHandler);
	#endif
	#if wxUSE_LIBJPEG
	wxImage::AddHandler(new wxJPEGHandler);
	#endif
	#if wxUSE_GIF
	wxImage::AddHandler(new wxGIFHandler);
	#endif
	principale = new MainFrame(NULL);
	principale->Show();
	// true = enter the main loop
	return true;
}
////////////////////////////////////////////////////////////////////////////////
// main application Frame implementation 
////////////////////////////////////////////////////////////////////////////////

/***********************************************
 * FRAME PRINCIPALE
 * *********************************************/
MainFrame::MainFrame(wxWindow *parent) : MainFrameBase( parent )
{
SetIcon(wxICON(iconFrame));
}
MainFrame::~MainFrame()
{
}
void MainFrame::OnCloseFrame(wxCloseEvent& event) //Chiusura box
{
	if (CLO){
	Destroy();
}
else {wxMessageBox("Chiudere prima la finestra clienti ... !",
			             "Avviso", wxOK | wxICON_EXCLAMATION);
clienti->SetFocus();}
}
void MainFrame::OnExitClick(wxCommandEvent& event) //Chiusura applicazione
{
    if (CLO){
	Destroy();
}
else {wxMessageBox("Chiudere prima la finestra clienti ... !",
			             "Avviso", wxOK | wxICON_EXCLAMATION);
clienti->SetFocus();}
}
void MainFrame::OnFrameOpen( wxCommandEvent& event ) //Apertura archivio clienti
{
	if (CLO){
	clienti =new MainFrame1(this);
	//(new MainFrame1(NULL))->Show();
	#if wxUSE_XPM
	wxImage::AddHandler(new wxXPMHandler);
	#endif
	#if wxUSE_LIBPNG
	wxImage::AddHandler(new wxPNGHandler);
	#endif
	#if wxUSE_LIBJPEG
	wxImage::AddHandler(new wxJPEGHandler);
	#endif
	#if wxUSE_GIF
	wxImage::AddHandler(new wxGIFHandler);
	#endif
	clienti->Show();
	CLO = false;
	principale->Enable(false);
	}
	clienti->SetFocus();
	clienti->m_bpButton12->Enable( false );
	
}
void MainFrame::OnFrameOpen3( wxCommandEvent& event ) //Apertura archivio fornitori
{
	if (CLO){
	fornitori =new MainFrame3(this);
	//(new MainFrame1(NULL))->Show();
	#if wxUSE_XPM
	wxImage::AddHandler(new wxXPMHandler);
	#endif
	#if wxUSE_LIBPNG
	wxImage::AddHandler(new wxPNGHandler);
	#endif
	#if wxUSE_LIBJPEG
	wxImage::AddHandler(new wxJPEGHandler);
	#endif
	#if wxUSE_GIF
	wxImage::AddHandler(new wxGIFHandler);
	#endif
	fornitori->Show();
	CLO = false;
	principale->Enable(false);
	}
	fornitori->SetFocus();
	fornitori->m_bpButton12->Enable( false );
}
void MainFrame::OnFrameOpen4( wxCommandEvent& event ) // Apertura archivio piano dei conti
{
	if (CLO){
	piaconti =new MainFrame4(this);
	//(new MainFrame1(NULL))->Show();
	#if wxUSE_XPM
	wxImage::AddHandler(new wxXPMHandler);
	#endif
	#if wxUSE_LIBPNG
	wxImage::AddHandler(new wxPNGHandler);
	#endif
	#if wxUSE_LIBJPEG
	wxImage::AddHandler(new wxJPEGHandler);
	#endif
	#if wxUSE_GIF
	wxImage::AddHandler(new wxGIFHandler);
	#endif
	piaconti->Show();
	CLO = false;
	principale->Enable(false);
	}
	piaconti->SetFocus();
}
/***********************************************
 * FRAME CLIENTI
 * *********************************************/
 MainFrame1::MainFrame1( wxWindow* parent ):MyFrame1( parent )
{
SetIcon(wxICON(iconFrame));
}
MainFrame1::~MainFrame1()
{
}
void MainFrame1::OnCloseFrame( wxCloseEvent& event ) //Chiusura box clienti
{
	principale->Enable(true);
	clo();
	Destroy();
}
void MainFrame1::OnClickClose(wxCommandEvent& event)
{
	principale->Enable(true);
	clo();
	Destroy();
}
/***********************************************
 * FRAME FORNITORI
 * *********************************************/
MainFrame3::MainFrame3( wxWindow* parent ):MyFrame3( parent )
{
SetIcon(wxICON(iconFrame));
}
MainFrame3::~MainFrame3()
{
}
void MainFrame3::OnCloseFrame( wxCloseEvent& event ) //Chiusura box fornitori
{
	principale->Enable(true);
	clo();
	Destroy();
}
void MainFrame3::OnClickClose(wxCommandEvent& event)
{
	principale->Enable(true);
	clo();
	Destroy();
}
/***********************************************
 * FRAME PIANO DEI CONTI
 * *********************************************/
MainFrame4::MainFrame4( wxWindow* parent ):MyFrame4( parent )
{
SetIcon(wxICON(iconFrame));
}
MainFrame4::~MainFrame4()
{
}
void MainFrame4::OnCloseFrame( wxCloseEvent& event ) //Chiusura box piano dei conti
{
	principale->Enable(true);
	clo();
	Destroy();
}