/*********************************************************************
 * Name:      	main.cpp
 * Purpose:   	Implements simple wxWidgets application with GUI
 * 				created using wxFormBuilder.
 * Author:      Sala Carlo  
 * Created:   	02/02/2019
 * Copyright: 	
 * License:   	wxWidgets license (www.wxwidgets.org)
 * 
 * Notes:		Note that all GUI creation code is implemented in
 * 				guiApp.cpp source file which is generated by wxFormBuilder.
 *********************************************************************/

#include "main.h"

// initialize the application
IMPLEMENT_APP(MainApp);

////////////////////////////////////////////////////////////////////////////////
// application class implementation 
////////////////////////////////////////////////////////////////////////////////

bool MainApp::OnInit()
{
	#if wxUSE_XPM
	wxImage::AddHandler(new wxXPMHandler);
	#endif
	#if wxUSE_LIBPNG
	wxImage::AddHandler(new wxPNGHandler);
	#endif
	#if wxUSE_LIBJPEG
	wxImage::AddHandler(new wxJPEGHandler);
	#endif
	#if wxUSE_GIF
	wxImage::AddHandler(new wxGIFHandler);
	#endif
	principale = new MainFrame(NULL);
	principale->Show();
// creazione o verifica esistenza database
bool creato = false;
bool aggiornato = false;
testDBName ="CaSa.db";
if (!(wxFileExists(testDBName))) {
	db->Open(testDBName);
	db->Close();
	}
				db->Open(testDBName);
				if (!(db->TableExists(wxT("Clienti")))) {
				creato = true;
				db->ExecuteUpdate(wxT("CREATE TABLE Clienti (ID integer primary key default null, RAG_SOC1 varchar(45), RAG_SOC2 varchar(45), INDIRIZZO varchar(40), CAP varchar(5), CITTA varchar(20), PROVINCIA varchar(2), NAZIONE varchar(12), CODFISC varchar(16), PFIS varchar(2), NPIVA varchar(2), PIVA varchar(11), TELEFONO varchar(15), FAX varchar(15), CELLULARE varchar(15), MAIL varchar(40), WEB varchar(40))"));}
				
				if (!(db->TableExists(wxT("Fornitori")))) {
				creato = true;
				db->ExecuteUpdate(wxT("CREATE TABLE Fornitori (ID integer primary key default null, RAG_SOC1 varchar(45), RAG_SOC2 varchar(45), INDIRIZZO varchar(40), CAP varchar(5), CITTA varchar(20), PROVINCIA varchar(2), NAZIONE varchar(12), CODFISC varchar(16), PFIS varchar(2), NPIVA varchar(2), PIVA varchar(11), TELEFONO varchar(15), FAX varchar(15), CELLULARE varchar(15), MAIL varchar(40), WEB varchar(40))"));}
				
				if (db->TableExists(wxT("Clienti"))) {
				set = db->ExecuteQuery("PRAGMA table_info(Clienti)");
				bool g=false;
				while (set.NextRow())
				{
				wxString M = set.GetAsString(1);	
				if (M=="PAG") {g=true;}
				}
				if(g == false){
				aggiornato = true;
				db->ExecuteUpdate(wxT("ALTER TABLE Clienti ADD COLUMN PAG varchar(3)"));}}
				
				if (db->TableExists(wxT("Fornitori"))) {
				set = db->ExecuteQuery("PRAGMA table_info(Fornitori)");
				bool g=false;
				while (set.NextRow())
				{
				wxString M = set.GetAsString(1);	
				if (M=="PAG") {g=true;}
				}
				if(g == false){
				aggiornato = true;
				db->ExecuteUpdate(wxT("ALTER TABLE Fornitori ADD COLUMN PAG varchar(3)"));}}

				if (db->TableExists(wxT("Clienti"))) {
				set = db->ExecuteQuery("PRAGMA index_list(Clienti)");
				bool g=false;
				while (set.NextRow())
				{
				wxString M = set.GetAsString(1);	
				if (M=="rag_soc") {g=true;}
				}
				if(g == false){
				aggiornato = true;
				db->ExecuteUpdate(wxT("CREATE INDEX rag_soc ON Clienti(RAG_SOC1)"));}}
				
				if (db->TableExists(wxT("Fornitori"))) {
				set = db->ExecuteQuery("PRAGMA index_list(Fornitori)");
				bool g=false;
				while (set.NextRow())
				{
				wxString M = set.GetAsString(1);	
				if (M=="rag_soc1") {g=true;}
				}
				if(g == false){
				aggiornato = true;
				db->ExecuteUpdate(wxT("CREATE INDEX rag_soc1 ON Fornitori(RAG_SOC1)"));}}			
				
				if (creato) {
				wxMessageBox("Ho creato nel database le tabelle necessarie ... !",
			             "Avviso", wxOK | wxICON_INFORMATION);
				}
				if ((aggiornato) and (!creato)) {
				wxMessageBox("Ho aggiornato nel database le tabelle necessarie ... !",
			             "Avviso", wxOK | wxICON_INFORMATION);
				}
		db->Close();
	return true;
}
////////////////////////////////////////////////////////////////////////////////
// main application Frame implementation 
////////////////////////////////////////////////////////////////////////////////

/***********************************************
 * FRAME PRINCIPALE
 * *********************************************/
MainFrame::MainFrame(wxWindow *parent) : MainFrameBase( parent )
{
SetIcon(wxICON(iconFrame));
}
MainFrame::~MainFrame()
{
}
void MainFrame::OnCloseFrame(wxCloseEvent& event) //Chiusura box
{
	if (CLO){
	Destroy();
}
else {wxMessageBox("Chiudere prima le altre finestre ... !",
			             "Avviso", wxOK | wxICON_EXCLAMATION);
clienti->SetFocus();}
}
void MainFrame::OnExitClick(wxCommandEvent& event) //Chiusura applicazione
{
    if (CLO){
	Destroy();
}
else {wxMessageBox("Chiudere prima le altre finestre ... !",
			             "Avviso", wxOK | wxICON_EXCLAMATION);
clienti->SetFocus();}
}
void MainFrame::OnFrameOpen( wxCommandEvent& event ) //Apertura archivio clienti
{
	if (CLO){
	clienti =new MainFrame1(this);
	//(new MainFrame1(NULL))->Show();
	#if wxUSE_XPM
	wxImage::AddHandler(new wxXPMHandler);
	#endif
	#if wxUSE_LIBPNG
	wxImage::AddHandler(new wxPNGHandler);
	#endif
	#if wxUSE_LIBJPEG
	wxImage::AddHandler(new wxJPEGHandler);
	#endif
	#if wxUSE_GIF
	wxImage::AddHandler(new wxGIFHandler);
	#endif
	clienti->Show();
	CLO = false;
	principale->Enable(false);
	}
	clienti->SetFocus();
	clienti->m_bpButton12->Enable( false );
}
void MainFrame::OnFrameOpen3( wxCommandEvent& event ) //Apertura archivio fornitori
{
	if (CLO){
	fornitori =new MainFrame3(this);
	//(new MainFrame1(NULL))->Show();
	#if wxUSE_XPM
	wxImage::AddHandler(new wxXPMHandler);
	#endif
	#if wxUSE_LIBPNG
	wxImage::AddHandler(new wxPNGHandler);
	#endif
	#if wxUSE_LIBJPEG
	wxImage::AddHandler(new wxJPEGHandler);
	#endif
	#if wxUSE_GIF
	wxImage::AddHandler(new wxGIFHandler);
	#endif
	fornitori->Show();
	CLO = false;
	principale->Enable(false);
	}
	fornitori->SetFocus();
	fornitori->m_bpButton12->Enable( false );
}
void MainFrame::OnFrameOpen4( wxCommandEvent& event ) // Apertura archivio piano dei conti
{
	if (CLO){
	piaconti =new MainFrame4(this);
	//(new MainFrame1(NULL))->Show();
	#if wxUSE_XPM
	wxImage::AddHandler(new wxXPMHandler);
	#endif
	#if wxUSE_LIBPNG
	wxImage::AddHandler(new wxPNGHandler);
	#endif
	#if wxUSE_LIBJPEG
	wxImage::AddHandler(new wxJPEGHandler);
	#endif
	#if wxUSE_GIF
	wxImage::AddHandler(new wxGIFHandler);
	#endif
	piaconti->Show();
	CLO = false;
	principale->Enable(false);
	}
	piaconti->SetFocus();
}
/***********************************************
 * FRAME CLIENTI
 * *********************************************/
 MainFrame1::MainFrame1( wxWindow* parent ):MyFrame1( parent )
{
SetIcon(wxICON(iconFrame));
}
MainFrame1::~MainFrame1()
{
}
void MainFrame1::OnCloseFrame( wxCloseEvent& event ) //Chiusura box clienti
{
	principale->Enable(true);
	clo();
	Destroy();
}
void MainFrame1::OnClickClose(wxCommandEvent& event)
{
	principale->Enable(true);
	clo();
	Destroy();
}
/***********************************************
 * FRAME FORNITORI
 * *********************************************/
MainFrame3::MainFrame3( wxWindow* parent ):MyFrame3( parent )
{
SetIcon(wxICON(iconFrame));
}
MainFrame3::~MainFrame3()
{
}
void MainFrame3::OnCloseFrame( wxCloseEvent& event ) //Chiusura box fornitori
{
	principale->Enable(true);
	clo();
	Destroy();
}
void MainFrame3::OnClickClose(wxCommandEvent& event)
{
	principale->Enable(true);
	clo();
	Destroy();
}
/***********************************************
 * FRAME PIANO DEI CONTI
 * *********************************************/
MainFrame4::MainFrame4( wxWindow* parent ):MyFrame4( parent )
{
SetIcon(wxICON(iconFrame));
}
MainFrame4::~MainFrame4()
{
}
void MainFrame4::OnCloseFrame( wxCloseEvent& event ) //Chiusura box piano dei conti
{
	principale->Enable(true);
	clo();
	Destroy();
}